# Generated by Django 3.2.16 on 2024-04-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexionp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexion',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
