# Generated by Django 3.2.16 on 2024-05-31 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conexionp', '0002_conexion_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conexion',
            options={'verbose_name': 'Conexion', 'verbose_name_plural': 'conexion Panelera'},
        ),
    ]
