# Generated by Django 3.2.16 on 2024-05-31 03:55

import apps.conexionp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexionp', '0003_alter_conexion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexion',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=apps.conexionp.models.boletines_thumbnail_directory),
        ),
    ]
