# Generated by Django 3.2.16 on 2024-04-09 13:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_multimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='images',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('image1', 'Image 1'), ('image2', 'Image 2'), ('image3', 'Image 3')], max_length=20),
        ),
    ]
