# Generated by Django 3.2.16 on 2024-04-09 13:26

import apps.news.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_multimedia_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='images',
        ),
        migrations.AddField(
            model_name='multimedia',
            name='image',
            field=models.ImageField(max_length=500, null=True, upload_to=apps.news.models.news_thumbnail_directory),
        ),
        migrations.CreateModel(
            name='ImgMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, null=True, upload_to=apps.news.models.news_thumbnail_directory)),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.multimedia')),
            ],
        ),
    ]
