# Generated by Django 3.2.16 on 2024-04-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20240409_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
