# Generated by Django 3.2.16 on 2024-04-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_multimedia_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgmultimedia',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
