# Generated by Django 3.2.16 on 2024-04-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_imgmultimedia_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time_read',
        ),
    ]
