# Generated by Django 3.2.16 on 2024-04-09 14:16

import apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_post_time_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=apps.news.models.news_thumbnail_directory),
        ),
    ]
