# Generated by Django 3.2.16 on 2024-04-09 14:24

import apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_post_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachments',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.news.models.news_thumbnail_directory),
        ),
    ]
