# Generated by Django 3.2.16 on 2024-05-31 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',), 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
    ]
