# Generated by Django 3.2.16 on 2024-03-22 06:32

import apps.boletines.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.boletines.models.boletines_thumbnail_directory)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Boletin',
                'verbose_name_plural': 'Boletines',
            },
        ),
    ]
