# Generated by Django 3.2.16 on 2024-03-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='categoria',
            field=models.CharField(choices=[('tendencias', 'Tendencias'), ('news', 'News')], default='news', max_length=20),
        ),
    ]
