# Generated by Django 3.2.16 on 2024-03-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletines', '0002_boletin_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
