# Generated by Django 3.2.16 on 2024-05-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletines', '0003_boletin_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletin',
            name='categoria',
            field=models.CharField(choices=[('tendencias', 'Tendencias'), ('news', 'News'), ('precios', 'Precios')], default='news', max_length=20),
        ),
    ]
