# Generated by Django 3.2.16 on 2024-06-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletines', '0004_alter_boletin_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletinPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.URLField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Boletin de precios',
                'verbose_name_plural': 'Boletines de precios',
            },
        ),
    ]
