# Generated by Django 3.2.16 on 2024-06-04 17:53

import apps.boletines.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletines', '0005_boletinprecios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletinprecios',
            name='document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.boletines.models.boletines_thumbnail_directory),
        ),
    ]
