# Generated by Django 3.2.16 on 2024-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletines', '0006_alter_boletinprecios_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletinprecios',
            name='descripition',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
