# Generated by Django 3.2.16 on 2024-06-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletines', '0007_boletinprecios_descripition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletinprecios',
            old_name='descripition',
            new_name='description',
        ),
    ]
