# Generated by Django 3.2.16 on 2024-04-04 04:29

import apps.programas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.programas.models.boletines_thumbnail_directory)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
    ]
