# Generated by Django 3.2.16 on 2024-04-04 21:45

import apps.slides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.slides.models.slides_thumbnail_directory)),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
            },
        ),
    ]
