# Generated by Django 3.2.16 on 2024-04-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_rename_documentoexcel_directorioexcel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectorioExcel',
            new_name='DirectorioCentral',
        ),
    ]
